FROM __from_image__

ARG GIT_BRANCH
ENV GIT_BRANCH ${GIT_BRANCH:-master}



ADD help.html /etc/NAE/help.html
ADD AppDef.json /etc/NAE/AppDef.json
ADD xilinx_runtime.sh /usr/local/bin/xilinx_runtime.sh
RUN chmod 755 /usr/local/bin/xilinx_runtime.sh
