FROM __from_image__

ARG GIT_BRANCH
ENV GIT_BRANCH ${GIT_BRANCH:-master}

RUN apt-get -y update && \
    apt-get -y install curl && \
    curl -H 'Cache-Control: no-cache' \
        https://raw.githubusercontent.com/nimbix/image-common/$GIT_BRANCH/install-nimbix.sh \
        | bash -s -- --setup-nimbix-desktop --image-common-branch $GIT_BRANCH

ADD help.html /etc/NAE/help.html
ADD AppDef.json /etc/NAE/AppDef.json
ADD xilinx_runtime.sh /usr/local/bin/xilinx_runtime.sh
RUN chmod 755 /usr/local/bin/xilinx_runtime.sh
